// source: game_update.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.chefmoji.MapUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.chefmoji.OrderUpdate');
goog.require('proto.chefmoji.PlayerUpdate');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chefmoji.MapUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.chefmoji.MapUpdate.repeatedFields_, null);
};
goog.inherits(proto.chefmoji.MapUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chefmoji.MapUpdate.displayName = 'proto.chefmoji.MapUpdate';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.chefmoji.MapUpdate.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chefmoji.MapUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.chefmoji.MapUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chefmoji.MapUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chefmoji.MapUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    mapList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    playersList: jspb.Message.toObjectList(msg.getPlayersList(),
    proto.chefmoji.PlayerUpdate.toObject, includeInstance),
    orderList: jspb.Message.toObjectList(msg.getOrderList(),
    proto.chefmoji.OrderUpdate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chefmoji.MapUpdate}
 */
proto.chefmoji.MapUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chefmoji.MapUpdate;
  return proto.chefmoji.MapUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chefmoji.MapUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chefmoji.MapUpdate}
 */
proto.chefmoji.MapUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addMap(value);
      break;
    case 2:
      var value = new proto.chefmoji.PlayerUpdate;
      reader.readMessage(value,proto.chefmoji.PlayerUpdate.deserializeBinaryFromReader);
      msg.addPlayers(value);
      break;
    case 3:
      var value = new proto.chefmoji.OrderUpdate;
      reader.readMessage(value,proto.chefmoji.OrderUpdate.deserializeBinaryFromReader);
      msg.addOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chefmoji.MapUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chefmoji.MapUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chefmoji.MapUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chefmoji.MapUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMapList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getPlayersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.chefmoji.PlayerUpdate.serializeBinaryToWriter
    );
  }
  f = message.getOrderList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.chefmoji.OrderUpdate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string map = 1;
 * @return {!Array<string>}
 */
proto.chefmoji.MapUpdate.prototype.getMapList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.chefmoji.MapUpdate} returns this
 */
proto.chefmoji.MapUpdate.prototype.setMapList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.chefmoji.MapUpdate} returns this
 */
proto.chefmoji.MapUpdate.prototype.addMap = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.chefmoji.MapUpdate} returns this
 */
proto.chefmoji.MapUpdate.prototype.clearMapList = function() {
  return this.setMapList([]);
};


/**
 * repeated PlayerUpdate players = 2;
 * @return {!Array<!proto.chefmoji.PlayerUpdate>}
 */
proto.chefmoji.MapUpdate.prototype.getPlayersList = function() {
  return /** @type{!Array<!proto.chefmoji.PlayerUpdate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.chefmoji.PlayerUpdate, 2));
};


/**
 * @param {!Array<!proto.chefmoji.PlayerUpdate>} value
 * @return {!proto.chefmoji.MapUpdate} returns this
*/
proto.chefmoji.MapUpdate.prototype.setPlayersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.chefmoji.PlayerUpdate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.chefmoji.PlayerUpdate}
 */
proto.chefmoji.MapUpdate.prototype.addPlayers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.chefmoji.PlayerUpdate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.chefmoji.MapUpdate} returns this
 */
proto.chefmoji.MapUpdate.prototype.clearPlayersList = function() {
  return this.setPlayersList([]);
};


/**
 * repeated OrderUpdate order = 3;
 * @return {!Array<!proto.chefmoji.OrderUpdate>}
 */
proto.chefmoji.MapUpdate.prototype.getOrderList = function() {
  return /** @type{!Array<!proto.chefmoji.OrderUpdate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.chefmoji.OrderUpdate, 3));
};


/**
 * @param {!Array<!proto.chefmoji.OrderUpdate>} value
 * @return {!proto.chefmoji.MapUpdate} returns this
*/
proto.chefmoji.MapUpdate.prototype.setOrderList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.chefmoji.OrderUpdate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.chefmoji.OrderUpdate}
 */
proto.chefmoji.MapUpdate.prototype.addOrder = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.chefmoji.OrderUpdate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.chefmoji.MapUpdate} returns this
 */
proto.chefmoji.MapUpdate.prototype.clearOrderList = function() {
  return this.setOrderList([]);
};


