# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_buffers/emailconfirm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_buffers/emailconfirm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#protocol_buffers/emailconfirm.proto\"\xbb\x01\n\x11\x45mailConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.EmailConfirmation.ErrorCode\x12\x0f\n\x07totpkey\x18\x03 \x01(\t\"V\n\tErrorCode\x12\x10\n\x0c\x64oesnotexist\x10\x00\x12\x11\n\rprevconfirmed\x10\x01\x12\x11\n\rjustconfirmed\x10\x02\x12\x11\n\rotherfailures\x10\x03\x62\x06proto3'
)



_EMAILCONFIRMATION_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='EmailConfirmation.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='doesnotexist', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='prevconfirmed', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='justconfirmed', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='otherfailures', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=141,
  serialized_end=227,
)
_sym_db.RegisterEnumDescriptor(_EMAILCONFIRMATION_ERRORCODE)


_EMAILCONFIRMATION = _descriptor.Descriptor(
  name='EmailConfirmation',
  full_name='EmailConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='EmailConfirmation.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='EmailConfirmation.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totpkey', full_name='EmailConfirmation.totpkey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EMAILCONFIRMATION_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=227,
)

_EMAILCONFIRMATION.fields_by_name['status'].enum_type = _EMAILCONFIRMATION_ERRORCODE
_EMAILCONFIRMATION_ERRORCODE.containing_type = _EMAILCONFIRMATION
DESCRIPTOR.message_types_by_name['EmailConfirmation'] = _EMAILCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailConfirmation = _reflection.GeneratedProtocolMessageType('EmailConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _EMAILCONFIRMATION,
  '__module__' : 'protocol_buffers.emailconfirm_pb2'
  # @@protoc_insertion_point(class_scope:EmailConfirmation)
  })
_sym_db.RegisterMessage(EmailConfirmation)


# @@protoc_insertion_point(module_scope)
