# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginconfirm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loginconfirm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12loginconfirm.proto\"\xab\x01\n\x11LoginConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.LoginConfirmation.ErrorCode\"W\n\tErrorCode\x12\x0c\n\x08\x62\x61\x64input\x10\x00\x12\x0e\n\nincooldown\x10\x01\x12\x0f\n\x0bnotverified\x10\x02\x12\x08\n\x04good\x10\x03\x12\x11\n\rotherfailures\x10\x04\x62\x06proto3'
)



_LOGINCONFIRMATION_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='LoginConfirmation.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='badinput', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='incooldown', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notverified', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='good', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='otherfailures', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=107,
  serialized_end=194,
)
_sym_db.RegisterEnumDescriptor(_LOGINCONFIRMATION_ERRORCODE)


_LOGINCONFIRMATION = _descriptor.Descriptor(
  name='LoginConfirmation',
  full_name='LoginConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='LoginConfirmation.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='LoginConfirmation.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGINCONFIRMATION_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=194,
)

_LOGINCONFIRMATION.fields_by_name['status'].enum_type = _LOGINCONFIRMATION_ERRORCODE
_LOGINCONFIRMATION_ERRORCODE.containing_type = _LOGINCONFIRMATION
DESCRIPTOR.message_types_by_name['LoginConfirmation'] = _LOGINCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginConfirmation = _reflection.GeneratedProtocolMessageType('LoginConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _LOGINCONFIRMATION,
  '__module__' : 'loginconfirm_pb2'
  # @@protoc_insertion_point(class_scope:LoginConfirmation)
  })
_sym_db.RegisterMessage(LoginConfirmation)


# @@protoc_insertion_point(module_scope)
