# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_action.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_action.proto',
  package='chefmoji',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13player_action.proto\x12\x08\x63hefmoji\"!\n\x0cPlayerAction\x12\x11\n\tkey_press\x18\x01 \x01(\x0c\x62\x06proto3'
)




_PLAYERACTION = _descriptor.Descriptor(
  name='PlayerAction',
  full_name='chefmoji.PlayerAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_press', full_name='chefmoji.PlayerAction.key_press', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['PlayerAction'] = _PLAYERACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerAction = _reflection.GeneratedProtocolMessageType('PlayerAction', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERACTION,
  '__module__' : 'player_action_pb2'
  # @@protoc_insertion_point(class_scope:chefmoji.PlayerAction)
  })
_sym_db.RegisterMessage(PlayerAction)


# @@protoc_insertion_point(module_scope)
