# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_buffers/signupconfirm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_buffers/signupconfirm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$protocol_buffers/signupconfirm.proto\"\xc6\x01\n\x12SignUpConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12,\n\x05\x65mail\x18\x02 \x01(\x0e\x32\x1d.SignUpConfirmation.ErrorCode\x12/\n\x08playerid\x18\x03 \x01(\x0e\x32\x1d.SignUpConfirmation.ErrorCode\"@\n\tErrorCode\x12\x08\n\x04good\x10\x00\x12\r\n\tnotunique\x10\x01\x12\x0c\n\x08notclean\x10\x02\x12\x0c\n\x08notvalid\x10\x03\x62\x06proto3'
)



_SIGNUPCONFIRMATION_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='SignUpConfirmation.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='good', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notunique', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notclean', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notvalid', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=175,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_SIGNUPCONFIRMATION_ERRORCODE)


_SIGNUPCONFIRMATION = _descriptor.Descriptor(
  name='SignUpConfirmation',
  full_name='SignUpConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='SignUpConfirmation.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='SignUpConfirmation.email', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playerid', full_name='SignUpConfirmation.playerid', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNUPCONFIRMATION_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=239,
)

_SIGNUPCONFIRMATION.fields_by_name['email'].enum_type = _SIGNUPCONFIRMATION_ERRORCODE
_SIGNUPCONFIRMATION.fields_by_name['playerid'].enum_type = _SIGNUPCONFIRMATION_ERRORCODE
_SIGNUPCONFIRMATION_ERRORCODE.containing_type = _SIGNUPCONFIRMATION
DESCRIPTOR.message_types_by_name['SignUpConfirmation'] = _SIGNUPCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignUpConfirmation = _reflection.GeneratedProtocolMessageType('SignUpConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPCONFIRMATION,
  '__module__' : 'protocol_buffers.signupconfirm_pb2'
  # @@protoc_insertion_point(class_scope:SignUpConfirmation)
  })
_sym_db.RegisterMessage(SignUpConfirmation)


# @@protoc_insertion_point(module_scope)
