# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_buffers/signupconfirm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_buffers/signupconfirm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$protocol_buffers/signupconfirm.proto\"\x9b\x01\n\x12SignUpConfirmation\x12\x10\n\x08password\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\x08\x12\x32\n\x08username\x18\x03 \x01(\x0e\x32 .SignUpConfirmation.UsernameCode\"0\n\x0cUsernameCode\x12\x08\n\x04good\x10\x00\x12\n\n\x06unique\x10\x01\x12\n\n\x06length\x10\x02\x62\x06proto3'
)



_SIGNUPCONFIRMATION_USERNAMECODE = _descriptor.EnumDescriptor(
  name='UsernameCode',
  full_name='SignUpConfirmation.UsernameCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='good', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unique', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='length', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=148,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_SIGNUPCONFIRMATION_USERNAMECODE)


_SIGNUPCONFIRMATION = _descriptor.Descriptor(
  name='SignUpConfirmation',
  full_name='SignUpConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='SignUpConfirmation.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='SignUpConfirmation.email', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='SignUpConfirmation.username', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNUPCONFIRMATION_USERNAMECODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=196,
)

_SIGNUPCONFIRMATION.fields_by_name['username'].enum_type = _SIGNUPCONFIRMATION_USERNAMECODE
_SIGNUPCONFIRMATION_USERNAMECODE.containing_type = _SIGNUPCONFIRMATION
DESCRIPTOR.message_types_by_name['SignUpConfirmation'] = _SIGNUPCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignUpConfirmation = _reflection.GeneratedProtocolMessageType('SignUpConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPCONFIRMATION,
  '__module__' : 'protocol_buffers.signupconfirm_pb2'
  # @@protoc_insertion_point(class_scope:SignUpConfirmation)
  })
_sym_db.RegisterMessage(SignUpConfirmation)


# @@protoc_insertion_point(module_scope)
