#!/bin/bash
curl -L -o protobuf.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-osx-x86_64.zip
unzip protobuf.zip && rm protobuf.zip
cp -R include/google /usr/local/include
mv bin/protoc /usr/local/bin/protoc
rm -r bin include
rm readme.txt